### ISSUE TITLE
 the training gets stuck at "caffe_solver.step(1)"

### ISSUE THREAD

**Issue by Belinda-great** [ShaoqingRen/faster_rcnn#107]
when i trained, using voc2007 data,  stage1_rpn is ok，at stage1_fast_rcnn, the training gets stuck at "caffe_solver.step(1)"(check_memery_gpu(...)), but  @"script_faster_rcnn_demo.m" detect no problem.
Could anyone give me some suggestions? Thanks!

**Comment by Belinda-great** [comment]
The troubling   Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE

**Comment by ArcherFMY** [comment]
@Belinda-great I met the same error with you, do you fix it?

**Comment by Belinda-great** [comment]
I used GTX1060 and cuda7.5，the error happened。I used cuda8.0，it solved。

发自我的 iPhone

**Comment by ArcherFMY** [comment]
@Belinda-great me too.  GTX 10~series may not work well with cuda 7.5.    I installed the cuda 8.0 and it worked.

Thx~
