### ISSUE TITLE
Prototxt files for faster rcnn

### ISSUE THREAD

**Issue by srikanthmg85** [ShaoqingRen/faster_rcnn#11]
Hi,  I am unable to find solver and training prototxt files required for training rpn and fast rcnn model.

**Comment by ShaoqingRen** [comment]
@srikanthmg85 You can download them by fetch_data/fetch_model_ZF.m and
fetch_data/fetch_model_VGG16.m

**Comment by srikanthmg85** [comment]
Got it, thank you.
