### ISSUE TITLE
Some issues with CUDA 8.0 and 6.5

### ISSUE THREAD

**Issue by paulhzx** [ShaoqingRen/faster_rcnn#117]
I use GTX1080, Windows 8.1 and Matlab 2014b. 
If I use cuda 8.0, I have the problem that Invalid MEX-file '**\caffe\matlab\caffe_faster_rcnn\caffe_.mexw64'.
If I use cuda 6.5, this issue would be solved, but I have new issue that Error using Caffe_, glog check error, please check log and clear mex.
I checked my log file, and the infomation is:
F0921 15:40:37.334478   424 math_functions.cu:422] Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE
F0921 15:40:37.334478   424 math_functions.cu:422] Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE

So, what should I do? If you have any solution, please let me know. Thanks!

**Comment by paulhzx** [comment]
The details about the issue:
`Error using Caffe_, glog check error, please check log and clear mex.
Error caffe.Solver/step (line 56)
      caffe_('solver_step', self.hSolver_self, iters);

Error fast_rcnn_train>check_gpu_memory (line 223)
    caffe_solver.step(1);

Error fast_rcnn_train (line 96)
    check_gpu_memory(conf, caffe_solver, num_classes, opts.do_val);

Error Faster_RCNN_Train.do_fast_rcnn_train (line 7)
    model_stage.output_model_file = fast_rcnn_train(conf, dataset.imdb_train, dataset.roidb_train, ...

Error script_faster_rcnn_Ships_ZF (line 53)
model.stage1_fast_rcnn      = Faster_RCNN_Train.do_fast_rcnn_train(conf_fast_rcnn, dataset, model.stage1_fast_rcnn, opts.do_val);`

**Comment by jxgu1016** [comment]
If you use cuda 8.0, you have  to recompile the .mexw64 file following the [guide.](https://github.com/ShaoqingRen/caffe/tree/faster-R-CNN). But after this, there still some pros rebuilding the `faster_rcnn_build.m`.  So has anyone successfully run it with cuda 8.0?????????

**Comment by zhongjunping** [comment]
I have the same problem, Have you sloved it @paulhzx ?

**Comment by lixiang-ucas** [comment]
I have the same problem, Have you sloved it @paulhzx ?

**Comment by smg478** [comment]
I had a frustrated week trying to compile the mex file using CUDA 8.0 on a Windows 10 machine (CUDA 6.5 is not compatible with Win 10.). Failed. Then installed windows 7, which is compatible with CUDA 6.5. It worked finally.

**Comment by paulhzx** [comment]
I have solved this issue. Just need to compile caffe with your own computer(cuda 8.0 an so on). There is Caffe fork that supports Faster R-CNN: https://github.com/ShaoqingRen/caffe/tree/faster-R-CNN

**Comment by raymondsa** [comment]
I had  the same error when i run faster CNN+WIN10+MATLAB2015+CUDA 8.0 GPU  GTX1080.
The solution was:
https://github.com/ShaoqingRen/caffe/tree/faster-R-CNN
