### ISSUE TITLE
out of memory in the training and resume training?

### ISSUE THREAD

**Issue by rachelmint** [ShaoqingRen/faster_rcnn#13]
I got out of memory error in the middle of Faster_RCNN_Train.do_proposal_test, is that out of gpu memory? is there any batch size I can set to reduce the memory.

and I already trained stage 1 RPN, is there anyway I can resume training like caffe does? 

experiments: test (voc_2007_trainval) 7559/10022  time: 0.378s
experiments: test (voc_2007_trainval) 7560/10022  time: 0.339s
experiments: test (voc_2007_trainval) 7561/10022  time: 0.307s
experiments: test (voc_2007_trainval) 7562/10022  time: 0.467s
experiments: test (voc_2007_trainval) 7563/10022 {Error using <a href="matlab:matlab.internal.language.introspective.errorDocCallback('imresizemex')" style="font-weight:bold">imresizemex</a>
Out of memory. Type HELP MEMORY for your options.

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('imresize>resizeAlongDim', 'C:\Program Files\MATLAB\MATLAB Production Server\R2015a\toolbox\images\images\imresize.m', 762)" style="font-weight:bold">imresize>resizeAlongDim</a> (<a href="matlab: opentoline('C:\Program Files\MATLAB\MATLAB Production Server\R2015a\toolbox\images\images\imresize.m',762,0)">line 762</a>)
out = imresizemex(in, weights', indices', dim);

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('imresize', 'C:\Program Files\MATLAB\MATLAB Production Server\R2015a\toolbox\images\images\imresize.m', 169)" style="font-weight:bold">imresize</a> (<a href="matlab: opentoline('C:\Program Files\MATLAB\MATLAB Production Server\R2015a\toolbox\images\images\imresize.m',169,0)">line 169</a>)
        B = resizeAlongDim(B, dim, weights{dim}, indices{dim});

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('prep_im_for_blob', 'E:\software\faster_rcnn-master\utils\prep_im_for_blob.m', 14)" style="font-weight:bold">prep_im_for_blob</a> (<a href="matlab: opentoline('E:\software\faster_rcnn-master\utils\prep_im_for_blob.m',14,0)">line 14</a>)
        im = imresize(im, target_size, 'bilinear', 'antialiasing', false);

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('proposal_im_detect>get_image_blob', 'E:\software\faster_rcnn-master\functions\rpn\proposal_im_detect.m', 74)" style="font-weight:bold">proposal_im_detect>get_image_blob</a> (<a href="matlab: opentoline('E:\software\faster_rcnn-master\functions\rpn\proposal_im_detect.m',74,0)">line 74</a>)
        [blob, im_scales] = prep_im_for_blob(im, conf.image_means, conf.test_scales,
        conf.test_max_size);

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('proposal_im_detect', 'E:\software\faster_rcnn-master\functions\rpn\proposal_im_detect.m', 10)" style="font-weight:bold">proposal_im_detect</a> (<a href="matlab: opentoline('E:\software\faster_rcnn-master\functions\rpn\proposal_im_detect.m',10,0)">line 10</a>)
    [im_blob, im_scales] = get_image_blob(conf, im);

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('proposal_test', 'E:\software\faster_rcnn-master\functions\rpn\proposal_test.m', 80)" style="font-weight:bold">proposal_test</a> (<a href="matlab: opentoline('E:\software\faster_rcnn-master\functions\rpn\proposal_test.m',80,0)">line 80</a>)
            [boxes, scores, abox_deltas{i}, aanchors{i}, ascores{i}] =
            proposal_im_detect(conf, caffe_net, im);

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('Faster_RCNN_Train.do_proposal_test', 'E:\software\faster_rcnn-master\experiments\+Faster_RCNN_Train\do_proposal_test.m', 2)" style="font-weight:bold">Faster_RCNN_Train.do_proposal_test</a> (<a href="matlab: opentoline('E:\software\faster_rcnn-master\experiments\+Faster_RCNN_Train\do_proposal_test.m',2,0)">line 2</a>)
    aboxes                      = proposal_test(conf, imdb, ...

Error in
<a href="matlab:matlab.internal.language.introspective.errorDocCallback('script_faster_rcnn_VOC2007_ZF>@(x,y)Faster_RCNN_Train.do_proposal_test(conf_proposal,model.stage1_rpn,x,y)', 'E:\software\faster_rcnn-master\experiments\script_faster_rcnn_VOC2007_ZF.m', 47)" style="font-weight:bold">script_faster_rcnn_VOC2007_ZF>@(x,y)Faster_RCNN_Train.do_proposal_test(conf_proposal,model.stage1_rpn,x,y)</a>
(<a href="matlab: opentoline('E:\software\faster_rcnn-master\experiments\script_faster_rcnn_VOC2007_ZF.m',47,0)">line 47</a>)
dataset.roidb_train        	= cellfun(@(x, y)
Faster_RCNN_Train.do_proposal_test(conf_proposal, model.stage1_rpn, x, y),
dataset.imdb_train, dataset.roidb_train, 'UniformOutput', false);

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('script_faster_rcnn_VOC2007_ZF', 'E:\software\faster_rcnn-master\experiments\script_faster_rcnn_VOC2007_ZF.m', 47)" style="font-weight:bold">script_faster_rcnn_VOC2007_ZF</a> (<a href="matlab: opentoline('E:\software\faster_rcnn-master\experiments\script_faster_rcnn_VOC2007_ZF.m',47,0)">line 47</a>)
dataset.roidb_train        	= cellfun(@(x, y)
Faster_RCNN_Train.do_proposal_test(conf_proposal, model.stage1_rpn, x, y),
dataset.imdb_train, dataset.roidb_train, 'UniformOutput', false);

**Comment by ShaoqingRen** [comment]
@rachelmint 
It seems that this out of memory is with CPU. Could you watch the usage of CPU memory ?

**Comment by rachelmint** [comment]
Here is my matlab cpu memory/virtual memory settings. I was training the ZF model with voc2007. I do notice my matlab java heap memory is set to default 384M, but I assume that will cause different error message?

Maximum possible array:     11708 MB (1.228e+10 bytes) *
Memory available for all arrays:     11708 MB (1.228e+10 bytes) *
Memory used by MATLAB:       834 MB (8.747e+08 bytes)
Physical Memory (RAM):      4095 MB (4.294e+09 bytes)

*  Limited by System Memory (physical + swap file) available.

>> systemview.VirtualAddressSpace

ans = 

    Available: 8.7900e+12
        Total: 8.7961e+12

**Comment by ShaoqingRen** [comment]
@rachelmint 

The proposal results need about 7000(images) * 6000(proposals) * 5(dim) * 4(bytes per float) ～  800MB. This corresponds to your information "Memory used by MATLAB: 834 MB (8.747e+08 bytes)".

So the problem seems not in the proposal framework. 

As the error stack, 
"Error in prep_im_for_blob (line 14)
im = imresize(im, target_size, 'bilinear', 'antialiasing', false);"
the error is throwed by imresize
please check the input parameters of "imresize".

**Comment by rachelmint** [comment]
I increase java heap space to 1G and virtual memory to 20G, the problem solved.

**Comment by Astrosun** [comment]
@rachelmint , Hi, rachelmint,
Just check with you whether there is a way to resume training such as in your case? I think the way to resume the training will be quite help if you lose your power or any other things happen in the middle of training.

Thanks

**Comment by rachelmint** [comment]
It has been a while so I cannot remember exactly now, but I think the code will skip a training if the trained model in that stage exists. There is no snapshot file as the original caffe does, so if you lost power and no model is generated you might need to training that model again.

**Comment by Astrosun** [comment]
@rachelmint 

Thanks for your answer. I think the code will generate snapshot files while training. I test it and it works.

Thanks!

**Comment by EveWYT** [comment]
Thank you very much! I have followed the steps to maximize the jave heap and swap, it also solve the problem.  My memory is 32G, and max java heap is 8G, but I have no swap space first, and it cannot work. When i create a swap space of 64G, it works out without problem, and i find it at least needs 15G to run 12_trainval
