### ISSUE TITLE
cannot open input file 'nms_gpu_mex.o'

### ISSUE THREAD

**Issue by dlahmad** [ShaoqingRen/faster_rcnn#137]
Dear community,

trying to compile faster rcnn i get the following errors:

Error using mex LINK : fatal error LNK1181: cannot open input file 'nms_gpu_mex.o'
Error in nvmex (line 48) eval(mexCommandLine);
Error in faster_rcnn_build (line 23) nvmex('functions/nms/nms_gpu_mex.cu', 'bin');

I can't find the reason for this and i don't find something using google.

Can someone help me?

Best Regards
Stephen

**Comment by Espenjt** [comment]
I encountered the same error and resorted to running the nms computation on the CPU instead.. It is rather time consuming, but works (in my case anyway). Have you resolved the issue? I would be very interested in a solution.

**Comment by jasmine89001** [comment]
Hi Espenjt,
I met the same question of fatal error LNK1181. Could you offer an solution about the detailed interpretation about change the nms computation on CPU? Thank you.

**Comment by Espenjt** [comment]
Hi Jasmine,
I haven't touched this in a while, but as far as i remember you just have to point every instance of 'nms_mex' to the accompanying CPU script 'nms'.

**Comment by dlahmad** [comment]
Outdated
