### ISSUE TITLE
Error using proposal_prepare_image_roidb>scale_rois (line 110) Non-singleton dimensions of the two input arrays must match each other.

### ISSUE THREAD

**Issue by abner2015** [ShaoqingRen/faster_rcnn#149]
Here is matlab err message
`Preparing training data...Starting parallel pool (parpool) using the 'local' profile ... connected to 6 workers.
Error using proposal_prepare_image_roidb>scale_rois (line 110)
Non-singleton dimensions of the two input arrays must match each other.

Error in proposal_prepare_image_roidb>@(x,y)compute_targets(conf,scale_rois(gt_rois,im_size,y),gt_labels,x,image_roidb_cell{i},y)
(line 60)
       bbox_targets{i} = cellfun(@(x, y) ...

Error in proposal_prepare_image_roidb>(parfor body) (line 60)
       bbox_targets{i} = cellfun(@(x, y) ...

Error in proposal_prepare_image_roidb>append_bbox_regression_targets (line 53)
    parfor i = 1:num_images

Error in proposal_prepare_image_roidb (line 43)
    [image_roidb, bbox_means, bbox_stds] = append_bbox_regression_targets(conf, image_roidb, bbox_means, bbox_stds);

Error in proposal_train (line 76)
    [image_roidb_train, bbox_means, bbox_stds]...

Error in Faster_RCNN_Train.do_proposal_train (line 7)
    model_stage.output_model_file = proposal_train(conf, dataset.imdb_train, dataset.roidb_train, ...

Error in script_faster_rcnn_VOC2007_ZF (line 48)
model.stage1_rpn            = Faster_RCNN_Train.do_proposal_train(conf_proposal, dataset, model.stage1_rpn, opts.do_val);
 `
Can anyone tell me how can I solve this problem? TH!

**Comment by abner2015** [comment]
Has been solved !
The cause of the problem is  the xml file format is wrong.
you can transform 'space' to 'tab'.

**Comment by raymondsa** [comment]
Check 'imdb\cache\roidb_voc_2007_train_flip_easy', in my case it was empty, this means can not read the .xml file.
Check the XML files format , for parsing the XML annotation files try to replace 'xml2struct.m' with
http://www.stat.ucla.edu/~zyyao/data/backup/databaseProject/labelMe/xml2struct.m

**Comment by raymondsa** [comment]
Check 'imdb\cache\roidb_voc_2007_train_flip_easy', in my case it was empty, this means can not read the .xml file.
Check the XML files format , for parsing the XML annotation files try to replace 'xml2struct.m' with
http://www.stat.ucla.edu/~zyyao/data/backup/databaseProject/labelMe/xml2struct.m
