### ISSUE TITLE
Does  selective_search  boxes  must  be  presented while training?

### ISSUE THREAD

**Issue by nopattern** [ShaoqingRen/faster_rcnn#15]
Dear ShaoqingRen:
      I am trying to use the code to train a ZF model  by running 'script_fast_rcnn_VOC2007_ZF". It
 failed though I have downloaded the required model and voc2007 dataset.  
      Then  "with_selective_search" option was disabled  by set "dataset.imdb_test.roidb_func(dataset.imdb_test, 'with_selective_search', false);".It failed again 
because a warning was outputed as "Warning: fast_rcnn_prepare_image_roidb: filter out 10022 
images, which contains zero valid samples".
    Does  selective_search  boxes  must  be  presented while training? What can I do to make train going down?

**Comment by ShaoqingRen** [comment]
@nopattern 

"script_fast_rcnn_VOC2007_ZF" is a script for 'fast r-cnn' not 'faster r-cnn'. This script not train RPN network, so selective_search is necessary. 
 
Please try "script_faster_rcnn_VOC2007_ZF". It does not need selective_search boxes.

**Comment by nopattern** [comment]
Thank you. I will try script_faster_rcnn_VOC2007_ZF.
