### ISSUE TITLE
Error while importing caffe module with faster rcnn

### ISSUE THREAD

**Issue by srikanthmg85** [ShaoqingRen/faster_rcnn#16]
Hi,
      I am trying to install new caffe module provided with faster-rcnn for having my own python interface to run faster-rcnn(instead of matlab). I have protobuf package version 2.4 installed. Could anyone help me with the error given below. I am able to build fast-rcnn without any problems. Thanks in advance. 

I am getting following error while importing caffe module:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/classic/faster_rcnn/faster_rcnn-master/external/caffe/caffe-faster-R-CNN/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/classic/faster_rcnn/faster_rcnn-master/external/caffe/caffe-faster-R-CNN/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: /home/classic/faster_rcnn/faster_rcnn-master/external/caffe/caffe-faster-R-CNN/python/caffe/../../build/lib/libcaffe.so: undefined symbol: _ZN6google8protobuf2io16CodedInputStream24default_recursion_limit_E

Thank you

**Comment by sunshineatnoon** [comment]
Hi, I am also interested in running faster rcnn in python instead of matlab, where should I start with?

**Comment by rbgirshick** [comment]
A python implementation is here:
https://github.com/rbgirshick/py-faster-rcnn.

**Comment by ShaoqingRen** [comment]
@srikanthmg85 @sunshineatnoon 
Ross has kindly provided a python version. 
You can easy-to-use this python verion.　:)

**Comment by ShaoqingRen** [comment]
@rbgirshick Thanks very much !

**Comment by sunshineatnoon** [comment]
@rbgirshick @ShaoqingRen Thanks!
