### ISSUE TITLE
Error in mAP

### ISSUE THREAD

**Issue by zhanglamei** [ShaoqingRen/faster_rcnn#17]
Hi,
I have trained model  with the file script_faster_rcnn_VOC2007_ZF.m already by commenting line 55 opts.mAP  = Faster_RCNN_Train.do_fast_rcnn_test(conf_fast_rcnn, model.stage1_fast_rcnn, dataset.imdb_test, dataset.roidb_test); 
and line 78 opts.final_mAP = Faster_RCNN_Train.do_fast_rcnn_test(conf_fast_rcnn, model.stage2_fast_rcnn, dataset.imdb_test, dataset.roidb_test);

If i didn't do that, error comes as follows:

Error using fprintf,
Invalid file identifier, use open to generate a file identifier.

Error in imdb_eval_voc(line 63)
fprintf(fid, '%s %f %.3f %.3f %.3f %.3f\n', image_ids{i}, bbox(j,end), bbox(j,1:4));

Error in fast_rcnn_test(line 171)
res(model_ind) = imdb.eval_func(cls, aboxes{model_ind}, imdb, opts.cache_name, opts.suffix);

Error in Faster_Rcnn_Train.do_fast_rcnn_test(line 6)
mAP = fast_rcnn_test(conf, imdb, roidb, ...
                                    'net_def_file',     model_stage.test_net_def_file, ...
                                    'net_file',         model_stage.output_model_file, ...
                                    'cache_name',       model_stage.cache_name, ...
                                    'ignore_cache',     ignore_cache);

Error in script_faster_rcnn_VOC2007_ZF(line 55)
opts.mAP = Faster_RCNN_Train.do_fast_rcnn_test(conf_fast_rcnn, model.stage1_fast_rcnn, dataset.imdb_test, dataset.roidb_test);

Thanks.

**Comment by ShaoqingRen** [comment]
@zhanglamei 

In imdb_eval_voc.m, we create a file to write the results. 
As Line 57 `fid = fopen(res_fn, 'w');`
It seems that there is something wrong in creating this file. Most probably it is because that the folder is missing.
Please check the parent folder of the file.

**Comment by zhanglamei** [comment]
@ShaoqingRen

Yes, you are right.
The error comes because the folder results in datasets/VOCdevkit2007 is missing.
Thank you !
