### ISSUE TITLE
ZF mAP on voc2007 lower than the log provided.

### ISSUE THREAD

**Issue by rachelmint** [ShaoqingRen/faster_rcnn#21]
Hi shaoqing,

I trained the ZF model on VOC2007 dataset by runing script_faster_rcnn_VOC2007_ZF.m and get an mAP ~55.6, this is lower than the ~59.4 mAP in you training log file (fast_rcnn_VOC2007_ZF/voc_2007_test/log/test_20150820_194058.txt).

Is there any difference between the 2 training processes? Here is my output
~~~~~~~~~~~~~~~~~~~~
Results:
   60.7088
   67.7598
   53.3626
   37.1256
   24.7806
   60.3213
   71.7281
   68.8887
   30.3973
   62.4456
   56.2178
   63.1661
   73.3527
   64.2983
   61.4177
   27.1311
   55.2103
   51.5869
   68.5139
   53.5203

   55.5967

~~~~~~~~~~~~~~~~~~~~
Cleared 0 solvers and 2 stand-alone nets
please modify detection_test.prototxt file for sharing conv layers with proposal model (delete layers until relu5

**Comment by ShaoqingRen** [comment]
@rachelmint 
As we expected, the model and code is exactly the same. 
If you ran script_faster_rcnn_VOC2007_ZF.m, then the corresponding log is in `output/fast_rcnn/cachedir/faster_rcnn_VOC2007_ZF_top-1_nms0_7_top2000_stage2_fast_rcnn/voc_2007_test/log/test_20150823_075759.txt`
Please compare this log with yours, or could you kindly send yours to me :)

**Comment by rachelmint** [comment]
Hi shaoqing,
Here is the train and test log in my \fast_rcnn_cachedir\faster_rcnn_VOC2007_ZF_top-1_nms0_7_top2000_stage2_fast_rcnn directory.

I tried training a few times and every time is the same mAP. Thx for help!

http://www.heypasteit.com/clip/28P5
http://www.heypasteit.com/clip/28P6

**Comment by rachelmint** [comment]
update:
I got lower mAP because i tried different parameters before and saved the results to cache. I did not clear all the cache files this time so the training resume based on cached files. I deleted all cache file and now everything is fine.

Btw, I found the detection_test.prototxt automatically generated in faster_rcnn_final foler/faster_rcnn_VOC2007_ZF/ is not right, it crashes matlab if I run the demo script. I copied the right prototxt file from the pretrained faster_rcnn_VOC0712_ZF model and that works fine.

**Comment by duygusar** [comment]
@rachelmint  Hi Rachelmint, I think I am having the problem you mentioned with the generated detection_test.prototxt I tried deleting till 5th layer and also replacing it with the final detection_test.prototxt provided by the authors, however both gives errors related to dimension mimatches etc and crashes Matlab. Which files did you change or replaced from exactly? Thanks!

**Comment by rachelmint** [comment]
I did it a month ago so cannot remember that clear, but I think I got it from the fetch_data function and downloaded shaoqing's pretrained model faster_rcnn_VOC0712_ZF. You may compare the 2 files (auto-generated and the one from the author) and fix the difference. I guess replacing the file directly may cause some other config in the prototxt wrong.

**Comment by duygusar** [comment]
@rachelmint  Thank you :) I just fixed it
