### ISSUE TITLE
cannot use caffe_ function in caffe_.mexa64

### ISSUE THREAD

**Issue by gliese581gg** [ShaoqingRen/faster_rcnn#22]
I tried to run 'script_faster_rcnn_demo.m' but I got this error

error: caffe.set_device (line 9)
caffe_('set_device', device_id);

Matlab said 'caffe_' is not defined.

Startup.m added 'external/caffe/matlab' without trouble and
I checked 'external/caffe/matlab/+caffe/private' folder and there is 'caffe_.mexa64' but it seems Matlab cannot use this file.

However, 'classification_demo.m' in 'external/caffe/matlab/demo' works.

Is there anyone who suffers same error?

**Comment by ShaoqingRen** [comment]
@gliese581gg 

The default path of caffe_ is in `fullfile(pwd, 'external', 'caffe', 'matlab', caffe_version)` or `fullfile(pwd, 'external', 'caffe', 'matlab')`, please check the path

**Comment by gliese581gg** [comment]
Problem solved!!

Thanks a lot :)

**Comment by RichardWenz** [comment]
Hi @gliese581gg  i got the same error as you, can you share how to solve this problem?i tried to post in someone thread also 10 days ago but there is no response. I hope you can help me. Thank you in advance.
