### ISSUE TITLE
File not found: .\models\rpn_prototxts\vgg_16layers_conv3_1\train_val.prototxt

### ISSUE THREAD

**Issue by naoto0804** [ShaoqingRen/faster_rcnn#30]
I tried to run 'script_faster_rcnn_VOC2007_VGG16.m' on Ubuntu14.04 but I got this error

F1031 20:05:16.437945 12590 io.cpp:34] Check failed: fd != -1 (-1 vs. -1) File not found: .\models\rpn_prototxts\vgg_16layers_conv3_1\train_val.prototxt

Of course, I've followed instructions and found the file exists in the same place.
In addition, I tried
addpath(genpath(fullfile(curdir, 'models')));
at startup.m.
But the error still remains. 
Is there anyone who suffers same error?

Thank you in advance.

**Comment by coallaoh** [comment]
I used to have the same error.
You have to change the back slashes (\) into forward slashes (/) in the solver prototxt.

**Comment by naoto0804** [comment]
It worked. Thank you so much!!

**Comment by wangjy2020** [comment]
@naoto0804 how to change the back slashes ()? Could you explain it clearly?

**Comment by naoto0804** [comment]
@wangjy2020 Please read coallaoh's comments below! Just modifying some .prototxt files.
