### ISSUE TITLE
Deep Residual Learning for Image Recognition paper availability

### ISSUE THREAD

**Issue by futurely** [ShaoqingRen/faster_rcnn#47]
@ShaoqingRen It is very exciting to know that your MSRA team have broken all the records on ImageNet classification, ImageNet detection, ImageNet localization, COCO detection, COCO segmentation and PASCAL VOC detection with large margins. Your achievements mark very significant milestones in the related areas. When and where will the ResNet paper [1] be released? Thanks a lot!

Sorry about that this question is not directly related to the project. I just can't wait to read the paper.

[1] "Deep Residual Learning for Image Recognition", Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun. Tech Report 2015.

**Comment by ShaoqingRen** [comment]
The paper can be found in  http://arxiv.org/abs/1512.03385.

**Comment by futurely** [comment]
The new architecture is so simple to implement and the results are so strong that you might win the ICCV Best Paper Award (Marr Prize). It is certain that all the types of deep neural network models will adopt residual learning and gain consistent performance improvements very soon.

Unfortunately, the paper did not mention the details of your segmentation algorithm. We will have to wait for another paper focus on that topic.

**Comment by n3011** [comment]
@ShaoqingRen any hint on implementing it using caffe? @futurely

**Comment by futurely** [comment]
Several examples are available in MXNet, Keras and Lasagne. https://github.com/dmlc/mxnet/issues/931

**Comment by futurely** [comment]
Caffe: https://github.com/beijbom/beijbom_python_lib/blob/master/beijbom_caffe_tools.py

**Comment by webmaven** [comment]
How about TensorFlow?

**Comment by gcr** [comment]
A warning: Quite a few of these implementations seem to be adding ReLU after every convolution layer. That doesn't seem right to me. If your building block is `y = ReLU(f(x)) + x`, then every layer will only *increase* `y` and *never decrease* `y` because one of the terms of the addition is constrained to be nonnegative.

The original paper only uses ReLU just after the addition `y = ReLU(f(x) + x)`, and right after the first (but not the second) convolution layer.

**Comment by erogol** [comment]
@gcr good point

**Comment by liuguiyangnwpu** [comment]
I want to use tensorflow to complish the residual network of MSAR. Who can give me some code support ! Not the paper ! Thx!

**Comment by futurely** [comment]
https://github.com/tensorflow/skflow/blob/master/examples/resnet.py

**Comment by yihui-he** [comment]
[The above residual network example of tensorflow has been moved here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/resnet.py)
