### ISSUE TITLE
 Link of 'bin\nms_gpu_mex.mexw64' failed. 

### ISSUE THREAD

**Issue by Cogito2012** [ShaoqingRen/faster_rcnn#49]
When I run the faster_rcnn_build.m, I encountered the problem like this:
//////////////////////////////////////////////////////////////////////////
......
nms_gpu_mex.cu 
mex -outdir bin nms_gpu_mex.o -L"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\lib\x64" -lcudart
libcpmt.lib(xthrow.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1700”不匹配值“1800”(nms_gpu_mex.o 中) 
libcpmt.lib(syserror.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1700”不匹配值“1800”(nms_gpu_mex.o 中) 
   正在创建库 C:\Users\WENTAO~1\AppData\Local\Temp\mex_qh9ZhZ\templib.x 和对象 C:\Users\WENTAO~1\AppData\Local\Temp\mex_qh9ZhZ\templib.exp 
nms_gpu_mex.o : error LNK2019: 无法解析的外部符号 fminf，该符号在函数 "float __cdecl fmin(float,float)" (?fmin@@YAMMM@Z) 中被引用 
nms_gpu_mex.o : error LNK2019: 无法解析的外部符号 fmaxf，该符号在函数 "float __cdecl fmax(float,float)" (?fmax@@YAMMM@Z) 中被引用 
......
 D:\PROGRAM FILES\MATLAB\R2013A\BIN\MEX.PL: Error: Link of 'bin\nms_gpu_mex.mexw64' failed. 
////////////////////////////////////////////////////////////////////////////
My platform is Matlab2013a + CUDA7.5 + VS2013compiler, how can I solve this problem?

**Comment by zhuyizi** [comment]
Hi,I meet the same question,How did you solve it?

**Comment by zhuyizi** [comment]
I solved this problem.You can modify the  Host_Compiler_Location in nvmex.m .
