### ISSUE TITLE
Matlab crashed when I run experiments/script_faster_rcnn_demo.m in Windows

### ISSUE THREAD

**Issue by Cogito2012** [ShaoqingRen/faster_rcnn#51]
I can successfully run script_faster_rcnn_demo.m with following configs:
opts.use_gpu                = false;
model_dir                   = fullfile(pwd, 'output', 'faster_rcnn_final', 'faster_rcnn_VOC0712_vgg_16layers'); %% VGG-16

opts.use_gpu                = false;
model_dir                   = fullfile(pwd, 'output', 'faster_rcnn_final', 'faster_rcnn_VOC0712_ZF'); %% ZF

opts.use_gpu                = true;
model_dir                   = fullfile(pwd, 'output', 'faster_rcnn_final', 'faster_rcnn_VOC0712_ZF'); %% ZF

But when I run it with this config:
opts.use_gpu                = true;
model_dir                   = fullfile(pwd, 'output', 'faster_rcnn_final', 'faster_rcnn_VOC0712_vgg_16layers'); %% VGG-16
My Matlab software crashed and shutdown with nothing tips, What's the problem?
PS: CUDA version is 7.5, Windows OS, Discrete Graphics is Quadro K620

**Comment by KapSteR** [comment]
You are likely running out of GPU memory when using the (very large) VGG network.
See the README for GPU hardware requirements.
