### ISSUE TITLE
training process will fail if the datasets has an image with no objects groundtruth

### ISSUE THREAD

**Issue by Cogito2012** [ShaoqingRen/faster_rcnn#52]
In the m file roidb_from_voc.m, the function attach_proposals(~) has some codes like this:
///////////////////////////////////////////////////
function rec = attach_proposals(voc_rec, boxes, class_to_id, exclude_difficult_samples, flip)
    ……
    if isfield(voc_rec, 'objects')
        ……
    else
        gt_boxes = [];
        all_boxes = boxes;
        gt_classes = [];
        num_gt_boxes = 0;
    end
//////////////////////////////////////////////////////
**So, when our datasets has a image with no objects, gt_boxes = [];** 

so in the script_faster_rcnn_VOC0712_ZF.m at  stage one proposal , this line:
model.stage1_rpn            = Faster_RCNN_Train.do_proposal_train(conf_proposal, dataset, model.stage1_rpn, opts.do_val);
will input dataset, and dataset.roidb_train(p).rois(q).boxes = [];

so int the file proposal_train.m with this line:
[image_roidb_train, bbox_means, bbox_stds]...
                            = proposal_prepare_image_roidb(conf, opts.imdb_train, opts.roidb_train);
will input opts.roidb_train, and opts.roidb_train(p).rois(q)  = [];

thus in the file proposal_prepare_image_roidb.m with this function will failed:
function scaled_rois = scale_rois(rois, im_size, im_scale)
    im_size_scaled = round(im_size * im_scale);
    scale = (im_size_scaled - 1) ./ (im_size - 1);
    scaled_rois = bsxfun(@times, rois-1, [scale(2), scale(1), scale(2), scale(1)]) + 1;
end
**Because rois = [], and bsxfun has two input array with different dimension, errors：**
//////////////////////////////////////////////////////////////////////////////////
Error using proposal_prepare_image_roidb>scale_rois (line
112)
Non-singleton dimensions of the two input arrays must match
each other.

Error in
proposal_prepare_image_roidb>@(x,y)compute_targets(conf,scale_rois(gt_rois,im_size,y),gt_labels,x,image_roidb_cell{i},y)
(line 62)
       bbox_targets{i} = cellfun(@(x, y) ...

Error in proposal_prepare_image_roidb>(parfor body) (line 62)
       bbox_targets{i} = cellfun(@(x, y) ...

Error in
proposal_prepare_image_roidb>append_bbox_regression_targets
(line 53)
    parfor i = 1:num_images

Error in proposal_prepare_image_roidb (line 43)
    [image_roidb, bbox_means, bbox_stds] =
    append_bbox_regression_targets(conf, image_roidb,
    bbox_means, bbox_stds);

Error in proposal_train (line 76)
    [image_roidb_train, bbox_means, bbox_stds]...

Error in Faster_RCNN_Train.do_proposal_train (line 7)
    model_stage.output_model_file = proposal_train(conf,
    dataset.imdb_train, dataset.roidb_train, ...

Error in script_faster_rcnn_pku (line 46)
model.stage1_rpn            =
Faster_RCNN_Train.do_proposal_train(conf_proposal, dataset,
model.stage1_rpn, opts.do_val);

Caused by:
    Error using bsxfun
    Non-singleton dimensions of the two input arrays must
    match each other.
///////////////////////////////////////////////////////////////////////////////////////////////

**So that means the previous if……else……end code block is wrong  ???**
**and how to deal with the problem when our image training dataset has no objects in a image ?**

**Comment by Dectinc** [comment]
Met the same problem.

Just remove the images without any objects from your training image list, for PASCOL VOC, it is VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt

**Comment by Cogito2012** [comment]
@Dectinc I had thought about this method, but it's hard because my dataset format is different from VOC. So I gave these images a small bounding box (such as [1,1,2,2] )  as their objects, do you think this method affects the whole training?

**Comment by Dectinc** [comment]
@Cogito2012 
not sure about this.
In fact, images that are involved in the training processes is provided by the an imdb database, in rbg's python version, the code can be found in lib/datasets. Thus, we're able to control the exact image set used for training.
Maybe you can try locating this process?

**Comment by Cogito2012** [comment]
@Dectinc OK, I'll have a try, thanks!
