### ISSUE TITLE
machine crash when running the code

### ISSUE THREAD

**Issue by 201power** [ShaoqingRen/faster_rcnn#58]
Hello, I am trying to running the code on

Ubuntu 12.04, MATLAB 2015a, Titan X 12G
cuda 7.0

However, the machine crashed after running 1-2 image of script_faster_rcnn_demo.m. 
I tried to comment use_cudnn=1, however, it crashed as well. 

I think it might because caffe ran out of memory. 
Do you know anywhere in the code I can change the batch size  of caffe?

Can you help?

**Comment by Anylee2142** [comment]
there are configuration difference between yours and mine.

but if i may to advise, 

1. uncomment 31 line of script_faster_rcnn_demo.m,

2. Change cuda 7.0 to cuda 6.5

Doing theses helped me from crashing

**Comment by 201power** [comment]
Thanks, I have other application depend on cuda 7.0, can I install both 6.5 and 7.0 in the system?

**Comment by Anylee2142** [comment]
@201power  
yes. but you should use 'nvcc -version' to set 6.5 to use.

here's the example of 'nvcc -version'

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>> nvcc -version
Cuda Toolkits Found : 
------------------------------------------------------------------
[1]  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin
------------------------------------------------------------------
Select the Cuda Toolkit you want to use : 1
.
Toolkit Path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin
Visual studio compilers Found : 
------------------------------------------------------------------
[1]  C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\
[2]  C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\
[3]  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\
------------------------------------------------------------------
Select the visual studio compiler you want to use : 1
.
VS Compiler: C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

As you can see, you can select among your current tools.

just make it 6.5, and nvccbat.bat file will be in current directory.

if you confirmed nvccbat.bat file, start over instructions.

**Comment by 201power** [comment]
I use Ubuntu, I don't think I can install two cuda...thanks anyway

**Comment by 201power** [comment]
@Anylee2142 I tried both
(1) uncomment 31. It still crash, and the log shows caffe is in the middle of loading network, the computer restarted
(2) I am now using cuda 6.5

Any other way to debug?

**Comment by Anylee2142** [comment]
@201power 

Well,, i solved mine with doing those..

I don't know why it still crashed..

Here below is what i have collected to solve script_faster_rcnn_demo, try these.

1.
comment 20 line, in script_faster_rcnn_demo
% model_dir = fullfile(pwd, 'output', 'faster_rcnn_final', 'faster_rcnn_VOC0712_vgg_16layers'); %% VGG-16

and uncomment 21 line  in script_faster_rcnn_demo
model_dir= fullfile(pwd, 'output', 'faster_rcnn_final', 'faster_rcnn_VOC0712_ZF'); %% ZF

after this, if imresize error appears, 
comment 27, 28, 52, 76 line in script_faster_rcnn_demo
%proposal_detection_model.conf_proposal.image_means=gpuArray(proposal_detection_model.conf_proposal.image_means);
%proposal_detection_model.conf_detection.image_means=gpuArray(proposal_detection_model.conf_detection.image_means);
%im = gpuArray(im);
or 
2.
at line 15, in script_faster_rcnn_demo,
change opts.use_gpu=true to false.

**Comment by 201power** [comment]
Thanks! It runs fine with ZF net in the demo.
However, I just tried ZF net training for VOC2007 dataset and it crashes. 

My machine normally crash (restart immediately) when out of memory. 
I am not sure if it's a Nvidia driver issue.

**Comment by Anylee2142** [comment]
Glad you can run it.

Did you got any textread error after script_faster_rcnn_VOC2007_ZF?

just crash error?

**Comment by 201power** [comment]
No I did not get any textread error, just crash on stage two.
Do you know how to change the batch size of ZF net?

**Comment by Anylee2142** [comment]
Afraid of telling you i don't.

Maybe you can check other issues related c-nn,

Searching c-nn, faster c-nn ,or any related issues about your problem may help

**Comment by 201power** [comment]
Thanks! I still think it's a memory related issue.  ZF require less memory compare to VGG. When I ran ZF demo, it's ok while the VGG crash. 

I also tried py-faster-rcnn and has the same issue. I tried CUDA 6.5, 7.0 and 7.5 and the machine always crash.

**Comment by 201power** [comment]
Solved by using a larger power supply

**Comment by MXLHELLO** [comment]
> Solved by using a larger power supply
“One thing I notice is, if I ran demo line by line, it won't crash,
However, when I ran the code without intervention, it will crash the machine.”
Helppppp!
Hello! I meet the same problem!!! 
What does "using a larger power" mean?

**Comment by MXLHELLO** [comment]
> Solved by using a larger power supply

“One thing I notice is, if I ran demo line by line, it won't crash,
However, when I ran the code without intervention, it will crash the machine.”

Helppppp!
Hello! I just meet the same problem!!!

What does "using a larger power supply" mean?
