### ISSUE TITLE
demo error: /sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by smajida** [ShaoqingRen/faster_rcnn#63]
Hi,

I'm goint to see the faster rcnn demo, but I'm getting the following error:

Invalid MEX-file '/BS/CNN_Image_Prior/work/caffe/matlab/+caffe/private/caffe_.mexa64':
/usr/lib/matlab-8.6/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found
(required by /BS/CNN_Image_Prior/work/caffe/matlab/+caffe/private/caffe_.mexa64)

but by following information there is 3.4.20 one.

$ls /usr/lib/x86_64-linux-gnu/libstdc++.so.6*
/usr/lib/x86_64-linux-gnu/libstdc++.so.6  /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20

$strings /usr/lib/matlab-8.6/sys/os/glnxa64/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.3.2
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH

how make GLIBCXX_3.4.20 here?

is the problem of mex? shall I make it again?
I received an error when "make matcaffe". error was regarding version of g++ claiming that 4.9.2 is not supported and 4.7 is supported. is this problem due to this issue?
if I change gcc to 4.7 and making caffe again, the problem is solved?
any help or advice is appreciated :)
#### 

$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.14
GLIBC_2.18
GLIBC_2.17
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by naoto0804** [comment]
Maybe this is helpful to you.
https://github.com/BVLC/caffe/issues/827
In my case, export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 solved the error.

**Comment by Achilles-96** [comment]
@naoto0804 
I did `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6`. I launched matlab from same terminal. Still the same error. Is there any othere way by which we have to add environment variables.

**Comment by AzmHmd** [comment]
@smajida @Achilles-96 Did you solve it?

if not go to [here](http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error)

**Comment by arasharchor** [comment]
yes it was solved. you have to change gcc and g++ version to be compatible.

LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21" matlab

**Comment by xuefeng-cvr** [comment]
yes，this page helps me to solve the problem.
My environment  is 
gcc 4.7
matlab 2016a
opencv 3.4.1

**Comment by SarKerson** [comment]
Thanks! This helpd me out!

**Comment by arasharchor** [comment]
if adding your own libstdc library does not work, you can add MATLAB's libstdc version to Makefile.config file below MATLAB_DIR.

LD_PRELOAD := /usr/local/MATLAB/R2018a/sys/os/glnxa64/libstdc++.so.6
