### ISSUE TITLE
gcc: error: nms_gpu_mex.o: No such file or directory

### ISSUE THREAD

**Issue by smajida** [ShaoqingRen/faster_rcnn#66]
When I open the matlab to see the demo after running function faster_rcnn_build()
I see the following error:

> > faster_rcnn_build
> > Compiling nms_mex
> > Building with 'g++'.
> > Warning: You are using gcc version '4.9.2'. The version of gcc is not supported. The version currently supported with MEX is '4.7.x'. For a list of
> > currently supported compilers see: http://www.mathworks.com/support/compilers/current_release. 
> > In faster_rcnn_build (line 13) 
> > Warning: You are using gcc version '4.9.2-10)'. The version of gcc is not supported. The version currently supported with MEX is '4.7.x'. For a list
> > of currently supported compilers see: http://www.mathworks.com/support/compilers/current_release. 
> > In faster_rcnn_build (line 13) 
> > MEX completed successfully.
> > Compiling nms_gpu_mex
> > /usr/local/cuda/bin/nvcc --compile   -o nms_gpu_mex.o  --compiler-options -fPIC  -I"/usr/lib/matlab-8.6/extern/include " -I/usr/local/cuda/include -I/usr/local/cuda/samples/common/inc "functions/nms/nms_gpu_mex.cu" 
> > /bin/bash: /usr/local/cuda/bin/nvcc: No such file or directory
> > mex -outdir bin nms_gpu_mex.o -L/usr/local/cuda/lib64 -lcudart
> > Building with 'gcc'.
> > Warning: You are using gcc version '4.9.2'. The version of gcc is not supported. The version currently supported with MEX is '4.7.x'. For a list of
> > currently supported compilers see: http://www.mathworks.com/support/compilers/current_release. 
> > In nvmex (line 48)
> >   In faster_rcnn_build (line 23) 
> > Warning: You are using gcc version '4.9.2-10)'. The version of gcc is not supported. The version currently supported with MEX is '4.7.x'. For a list
> > of currently supported compilers see: http://www.mathworks.com/support/compilers/current_release. 
> > In nvmex (line 48)
> >   In faster_rcnn_build (line 23) 
> > Error using mex
> > gcc: error: nms_gpu_mex.o: No such file or directory

Error in nvmex (line 48)
eval(mexCommandLine);

Error in faster_rcnn_build (line 23)
   nvmex('functions/nms/nms_gpu_mex.cu', 'bin');

If I ignore it and continue with the demo m file I get the following error:

How to resolve this problem? Shall i install gcc-4.7.x version?

**Comment by cmanders** [comment]
I have the same issue, plus, installing gcc 4.7 will not be so easy. If it was possible to use 4.8, that would make things easier

**Comment by ckmufeng** [comment]
I have the same problem。I use VS2013。

**Comment by rickeywang** [comment]
@ckmufeng  Thanks, that solved the problem for me. I have VS 2012 installed instead of VS 2013.

**Comment by arasharchor** [comment]
@ckmufeng thank a lot. I noticed that I had to change the location of CUDA library in nvmex.m. 
I am using Linux OS.

**Comment by June-Jo** [comment]
Hello. I had the same error in this issue, but I don't understand your solution. Can you explain the more detailed instroduction?

**Comment by pallavimitra** [comment]
Hello. I am getting the same error. I have using VS2013 and th epath is also coreect. still the error is like -

Error using mex
gcc: error: nms_gpu_mex.o: No such file or directory


Error in nvmex (line 48)
eval(mexCommandLine);

Error in faster_rcnn_build (line 23)
   nvmex('D:\PALLAVI\faster_rcnn-master\faster_rcnn-master\functions/nms/nms_gpu_mex.cu', 'bin');

Can anyone please help me in this issue?

**Comment by arasharchor** [comment]
i had to go to lib directory and delete all of files resulted in making in this folder. Then I did `make` again in `lib` directory and it worked.
