### ISSUE TITLE
Export features for each bounding box

### ISSUE THREAD

**Issue by Elpidam** [ShaoqingRen/faster_rcnn#75]
Helloo, I want to export for each bounding box (visualized) a feature vector , produced by a specific layer.  In fast_rcnn_conv_feat_detect there is `scores = caffe_net.blobs('cls_score').get_data();`. How can I use it in my situation by changing 'cls_score' with the name of the layer I want?

**Comment by yossibiton** [comment]
You just found the answer.
If you want for examples the features from 'fc7' layer run the same command with 'fc7' instead of 'cls_score'.
You should run it right after the forward pass.
