### ISSUE TITLE
Got Error "cannot find ./data/selective_search_data/voc_2007_trainval.mat" 

### ISSUE THREAD

**Issue by tingtinh** [ShaoqingRen/faster_rcnn#77]
Following the authors' instruction, I'm trying to train the model with ZF net. However when I run the file "experiments/script_faster_rcnn_VOC2007_ZF.m " I got this error:

Error using roidb_from_voc (line 44)
roidb_from_ilsvrc:: **cannot find ./data/selective_search_data/voc_2007_trainval.mat**

Error in Dataset.voc2007_trainval_ss>@(x)x.roidb_func(x,'with_selective_search',true) (line 12)
        dataset.roidb_train   = cellfun(@(x) x.roidb_func(x, 'with_selective_search', true), dataset.imdb_train, 'UniformOutput', false);

Error in Dataset.voc2007_trainval_ss (line 12)
        dataset.roidb_train   = cellfun(@(x) x.roidb_func(x, 'with_selective_search', true), dataset.imdb_train, 'UniformOutput', false);

Error in script_fast_rcnn_VOC2007_ZF (line 28)
dataset                     = Dataset.voc2007_trainval_ss(dataset, 'train', conf.use_flipped);

I'm confused why we need the selective_search_data when training Faster-RCNN which generates proposals by RPN? And if it's necessary for training how I can get the selective_search_data? I'm looking forward for any helpful answers. Thanks!

**Comment by 1SoSo** [comment]
@tingtinh I just ran into the same issue. It seems like you could solve it. Do you know now the answer to your question (which is also mine now ;) ) ? Why do we need selective_search data ?

**Comment by LXWDL** [comment]
I have encounter the same problem

**Comment by 1SoSo** [comment]
You use the wrong training script. Check that you really use the fastER R-cnn and not the fast R-cnn script. Hope that solves it already.

**Comment by miraclewkf** [comment]
It is faster RCNN,I also have this problem
