### ISSUE TITLE
caffe_faster_rcnn not built

### ISSUE THREAD

**Issue by KapSteR** [ShaoqingRen/faster_rcnn#9]
Hi... 

I'm on Ubuntu Linux 14.4, and i'm trying to run the example.

I get to the "Run `experiments/script_faster_rcnn_demo.m` to test a single demo image." point, but i get the error:

```
Error using cd
Cannot CD to
/home/kasper/masterthesis/faster_rcnn/experiments/external/caffe/matlab/caffe_faster_rcnn (Name
is nonexistent or not a directory).
```

I have built caffe with make like I've done a hundred times before with regular caffe, but the `caffe_faster_cnn` part does not seem to be built.

**Comment by rbgirshick** [comment]
@KapSteR you need to `mkdir external/caffe/matlab/caffe_faster_rcnn` and then `cp -r external/caffe/matlab/+caffe external/caffe/matlab/caffe_faster_rcnn`.

@ShaoqingRen we should add that to the instructions or change the code to use the matlab interface from its canonical location at `external/caffe/matlab` (not from `external/caffe/matlab/caffe_faster_rcnn`, which doesn't exist in the caffe repo).

**Comment by KapSteR** [comment]
@rbgirshick This worked for me, thank you...

**Comment by ShaoqingRen** [comment]
@rbgirshick I've added "external/caffe/matlab" as backup folder if “external/caffe/matlab/caffe_faster_rcnn" is not exist in utils/active_caffe_mex.m. Will this work with Makefile ?

**Comment by wangjy2020** [comment]
`Invalid MEX-file '/home/jingyi/Program/faster_rcnn/external/caffe/matlab/caffe_faster_rcnn/+caffe/private/caffe_.mexa64': Missing dependent
shared libraries:
'libhdf5_hl.so.100' required by '/home/jingyi/Program/faster_rcnn/external/caffe/matlab/caffe_faster_rcnn/+caffe/private/caffe_.mexa64'
'libhdf5.so.101' required by '/home/jingyi/Program/faster_rcnn/external/caffe/matlab/caffe_faster_rcnn/+caffe/private/caffe_.mexa64'`
