### ISSUE TITLE
K must less or equal to N?

### ISSUE THREAD

**Issue by chuxindi0325** [ShaoqingRen/faster_rcnn#93]
Error using randperm
K must be less than or equal to N.

Error in proposal_train (line 88)
        shuffled_inds_val   = shuffled_inds_val(randperm(length(shuffled_inds_val), opts.val_iters));

Error in Faster_RCNN_Train.do_proposal_train (line 7)
    model_stage.output_model_file = proposal_train(conf, dataset.imdb_train, dataset.roidb_train, ...

Error in script_faster_rcnn_VOC2007_ZF (line 45)
model.stage1_rpn            = Faster_RCNN_Train.do_proposal_train(conf_proposal, dataset,
model.stage1_rpn, opts.do_val);
 
IdleTimeout has been reached.
Parallel pool using the 'local' profile is shutting down.

**Comment by chuxindi0325** [comment]
should i modify the functions/fast_rcnn_config.m batch-size?

**Comment by hongzhangMu** [comment]
hello,I have the same issue. I don't know where to change the path. Have you solved this?

**Comment by chuxindi0325** [comment]
@hongzhangMu sorry,i have no idea about this problem.However i thought that it's not the problem on the path as I check the function .Have you solved now?

**Comment by yossibiton** [comment]
change 
shuffled_inds_val = shuffled_inds_val(randperm(length(shuffled_inds_val), opts.val_iters));

to :
shuffled_inds_val = shuffled_inds_val(randperm(length(shuffled_inds_val), min(length(shuffled_inds_val), opts.val_iters)));

**Comment by chuxindi0325** [comment]
@yossibiton I have sovled this problem by your method!Thanks a lot!!

**Comment by salahsh** [comment]
@yossibiton 
Thanks, it worked with me.
