### ISSUE TITLE
How to train faster_rcnn on objects with small size? If i need modify the size of anchors?

### ISSUE THREAD

**Issue by yytzjgsu** [ShaoqingRen/faster_rcnn#98]
I found that size of anchors may be not suitable for training a new model for detect small object.All images of  my own dataset is 1920x1080,but the object is only 18x9.So it is necessary to adjust the size of it?
Any reply will be appreciated.

**Comment by zzningxp** [comment]
The problem is not about the anchor size.
The code first scales the image from 1080p to 600p, then the small size object will lose the precision.
Thus, you can change this scale size.
